display_name: "Default Nation"
towns:
 0:
  display_name: "Capital"

ranks:
 recruit:
  display_name: "Recruit"
  permissions:
   - container
   - button
   - lever
   - door
 member:
  display_name: "Member"
  inherits: "recruit"
  permissions:
   - build
   - recruit
 officer:
  display_name: "Officer"
  inherits: "member"
  permissions:
   - demote
   - promote
   - claim
 leader:
  display_name: "Leader"
  inherits: "officer"
  permissions:
   - coffers
   - kick

members: