name: Espero
main: me.felnstaren.espero.Espero
version: 1.0.0a
author: Felnstaren
description: Core plugin for the Espero Server
api-version: 1.16

commands:
 rift:
  aliases: []
  description: Creates a rift
 test:
  aliases: []
  description: Development test command
 nation:
  aliases: [n]
  description: Default nation command