name: Espero
main: me.felnstaren.espero.Espero
version: 1.0.0a
author: Felnstaren
description: Core plugin for the Espero Server
api-version: 1.16
depend: [FeLib]

commands:
 rift:
  aliases: []
  description: Creates a rift
 test:
  aliases: []
  description: Development test command
 nation:
  aliases: [n]
  description: Default nation command
 town:
  aliases: [t]
  description: Default town command
 morph:
  aliases: []
  description: HeHe Packets go Brr
 combat:
  aliases: []
  description: How much longer will you be in combat?
 money:
  aliases: []
  description: Free money
 group:
  aliases: [grp]
  description: Espero groups command
